"""
Market Anomaly Detection Pipeline - Main Entry Point
"""

import argparse
import logging

from market_anomaly_detection.config import PipelineConfig
from market_anomaly_detection.pipelines.orchestrator import (
    MarketAnomalyDetectionPipeline,
)


def _configure_logging() -> logging.Logger:
    """Create a default logger for CLI usage."""
    logger = logging.getLogger("market_anomaly_detection")
    if not logger.handlers:
        logging.basicConfig(level=logging.INFO, format="%(message)s")
    return logger


def _write_outputs(
    pipeline: MarketAnomalyDetectionPipeline, results: dict, logger: logging.Logger
) -> None:
    """Persist outputs generated by the pipeline."""
    output_csv = pipeline.export_results()
    logger.info("\nResults saved to: %s", output_csv)

    logger.info("\nGenerating visualizations...")
    visualizations = results["visualizations"]
    for viz_name, fig in visualizations.items():
        output_html = str(pipeline.config.output_dir / f"{viz_name}.html")
        fig.write_html(output_html)
        logger.info("  - %s: %s", viz_name, output_html)

    stats = results["anomaly_stats"]
    logger.info("\n%60s", "Anomaly Detection Statistics")
    logger.info("%s", "-" * 60)
    logger.info("Total Records:        %10s", stats["total_records"])
    logger.info("Normal Points:        %10s", stats["normal_count"])
    logger.info("Anomalies Detected:   %10s", stats["anomaly_count"])
    logger.info("Anomaly Rate:         %9.2f%%", stats["anomaly_rate"])

    if "detailed_counts" in stats:
        counts = stats["detailed_counts"]
        logger.info("\n%60s", "Model-Specific Anomalies")
        logger.info("%s", "-" * 60)
        logger.info("IQR:                  %10s", counts.get("IQR", 0))
        logger.info("Z-Score:              %10s", counts.get("Z-Score", 0))
        logger.info("Isolation Forest:     %10s", counts.get("Isolation Forest", 0))
        logger.info("LOF:                  %10s", counts.get("LOF", 0))
        logger.info("Combined Model (All 4): %8s", counts.get("Combined", 0))

    pca_results = results["pca"]
    logger.info("\n%60s", "PCA Analysis")
    logger.info("%s", "-" * 60)
    for i, var in enumerate(pca_results["explained_variance"]):
        logger.info("PC%s Explained Variance: %8.2f%%", i + 1, var * 100)
    logger.info("Cumulative Variance:  %8.2f%%", pca_results["cumulative_variance"][-1] * 100)

    logger.info("\n%s", "=" * 60)
    logger.info("PIPELINE EXECUTION COMPLETED")
    logger.info("%s", "=" * 60)

    artifacts_dir = pipeline.save_artifacts("models")
    logger.info("Artifacts saved to: %s", artifacts_dir)


def main(
    write_outputs: bool = True, logger: logging.Logger | None = None
) -> MarketAnomalyDetectionPipeline:
    """Main execution function."""

    logger = logger or _configure_logging()
    config = PipelineConfig()
    pipeline = MarketAnomalyDetectionPipeline(config, logger=logger)
    results = pipeline.run()

    if write_outputs:
        _write_outputs(pipeline, results, logger)

    return pipeline


def cli_main() -> None:
    """Command-line entry point."""
    parser = argparse.ArgumentParser(description="Run the market anomaly detection pipeline.")
    parser.add_argument(
        "--no-output",
        action="store_true",
        help="Skip writing CSV, HTML visualizations, and artifacts.",
    )
    args = parser.parse_args()

    main(write_outputs=not args.no_output)


if __name__ == "__main__":
    cli_main()
